<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../__PROJECT__.Domain/__PROJECT__.Domain.csproj" />
    <ProjectReference Include="../__PROJECT__.Application/__PROJECT__.Application.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="LiteBus.Commands.Abstractions" />
    <PackageReference Include="LiteBus.Events.Abstractions" />
    <PackageReference Include="Marten" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks" />
    <PackageReference Include="Npgsql" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="__PROJECT__.Integration.Tests" />
  </ItemGroup>
</Project>
