using System.Text;
using Litenova.Standards.Models;

namespace Litenova.Standards.Services;

internal static class ConsumerGenerator
{
    private const string MarkdownMarker = "<!-- Generated by Litenova.Standards.Tool. Do not edit by hand. -->";

    public static IReadOnlyDictionary<string, string> Render(ConsumerRepository consumer)
    {
        var traces = CreateTraces(consumer);
        var domainRoot = consumer.Project.Paths.DomainDocs.TrimEnd('/');
        var uiRoot = consumer.Project.Paths.UiDocs.TrimEnd('/');

        return new Dictionary<string, string>(StringComparer.Ordinal)
        {
            [$"{domainRoot}/agent-index.json"] = JsonSupport.Serialize(new
            {
                generated = StandardsGenerator.GeneratedMarker,
                features = consumer.Features.Select(feature => new
                {
                    feature.Metadata.Id,
                    feature.Metadata.Status,
                    path = feature.Path,
                }),
                useCases = consumer.UseCases.Select(useCase => new
                {
                    useCase.Metadata.Id,
                    useCase.Metadata.Kind,
                    useCase.Metadata.Status,
                    useCase.Metadata.Actors,
                    useCase.Metadata.Surfaces,
                    assurance = useCase.Metadata.Criticality.Count == 0 ? "standard" : "critical",
                    useCase.Metadata.Recipes,
                    path = useCase.Path,
                }),
            }),
            [$"{domainRoot}/use-case-index.md"] = RenderUseCaseIndex(consumer),
            [$"{domainRoot}/traceability.json"] = JsonSupport.Serialize(new
            {
                generated = StandardsGenerator.GeneratedMarker,
                traces,
            }),
            [$"{domainRoot}/traceability.md"] = RenderTraceability(traces),
            [$"{uiRoot}/route-index.json"] = JsonSupport.Serialize(new
            {
                generated = StandardsGenerator.GeneratedMarker,
                pages = consumer.Pages.Select(page => new
                {
                    page.Metadata.Id,
                    page.Metadata.App,
                    page.Metadata.Route,
                    page.Metadata.UseCases,
                    path = page.Path,
                }),
            }),
        };
    }

    public static ValidationReport Validate(StandardsRepository standards, ConsumerRepository consumer)
    {
        var report = new ValidationReport();
        ValidatePaths(consumer, report);
        ValidateUniqueValues(consumer, report);
        ValidateRecipes(standards, consumer, report);
        ValidatePages(consumer, report);

        foreach (var useCase in consumer.UseCases.Where(item => item.Metadata.Status == "active"))
        {
            if (useCase.AcceptanceCriteria.Count == 0)
            {
                report.Error("USE_CASE_CRITERIA", "Active use case has no acceptance criteria.", useCase.Path);
            }

            foreach (var criterion in useCase.AcceptanceCriteria)
            {
                if (!consumer.TestReferences.TryGetValue(criterion, out var files) || files.Count == 0)
                {
                    report.Error("TRACE_MISSING", $"Active criterion {criterion} has no automated test reference.", useCase.Path);
                }
            }
        }

        return report;
    }

    public static void Write(ConsumerRepository consumer)
    {
        foreach (var (relativePath, content) in Render(consumer))
        {
            var path = Path.Combine(consumer.Root, relativePath.Replace('/', Path.DirectorySeparatorChar));
            Directory.CreateDirectory(Path.GetDirectoryName(path)!);
            File.WriteAllText(path, content);
        }
    }

    public static ValidationReport Check(StandardsRepository standards, ConsumerRepository consumer)
    {
        var report = Validate(standards, consumer);
        foreach (var (relativePath, expected) in Render(consumer))
        {
            var path = Path.Combine(consumer.Root, relativePath.Replace('/', Path.DirectorySeparatorChar));
            if (!File.Exists(path))
            {
                report.Error("CONSUMER_GENERATED_MISSING", "Generated consumer file is missing.", relativePath);
                continue;
            }

            var actual = File.ReadAllText(path).Replace("\r\n", "\n");
            if (!string.Equals(actual, expected, StringComparison.Ordinal))
            {
                report.Error("CONSUMER_GENERATED_STALE", "Generated consumer file is stale. Run standards generate --project standards.project.json.", relativePath);
            }
        }

        return report;
    }

    private static IReadOnlyList<AcceptanceTrace> CreateTraces(ConsumerRepository consumer) =>
        consumer.UseCases
            .SelectMany(useCase => useCase.AcceptanceCriteria.Select(criterion => new AcceptanceTrace(
                criterion,
                useCase.Metadata.Id,
                useCase.Path,
                consumer.TestReferences.GetValueOrDefault(criterion, []))))
            .OrderBy(trace => trace.Criterion, StringComparer.Ordinal)
            .ToArray();

    private static string RenderUseCaseIndex(ConsumerRepository consumer)
    {
        var builder = new StringBuilder();
        builder.AppendLine(MarkdownMarker);
        builder.AppendLine("# Use Cases");
        builder.AppendLine();
        foreach (var group in consumer.UseCases.GroupBy(useCase => useCase.Metadata.Id.Split('.')[0], StringComparer.Ordinal))
        {
            builder.AppendLine($"## {group.Key}");
            builder.AppendLine();
            foreach (var useCase in group)
            {
                var assurance = useCase.Metadata.Criticality.Count == 0 ? "standard" : "critical";
                builder.AppendLine($"- [{useCase.Metadata.Id}]({RelativeMarkdownLink($"{consumer.Project.Paths.DomainDocs}/use-case-index.md", useCase.Path)}) ({useCase.Metadata.Kind}, {useCase.Metadata.Status}, {assurance})");
            }

            builder.AppendLine();
        }

        return builder.ToString().Replace("\r\n", "\n");
    }

    private static string RenderTraceability(IReadOnlyList<AcceptanceTrace> traces)
    {
        var builder = new StringBuilder();
        builder.AppendLine(MarkdownMarker);
        builder.AppendLine("# Acceptance Traceability");
        builder.AppendLine();
        builder.AppendLine("| Criterion | Use case | Test files |");
        builder.AppendLine("|:---|:---|:---|");
        foreach (var trace in traces)
        {
            var files = trace.TestFiles.Count == 0 ? "Missing" : string.Join("<br>", trace.TestFiles.Select(file => $"`{file}`"));
            builder.AppendLine($"| `{trace.Criterion}` | `{trace.UseCase}` | {files} |");
        }

        return builder.ToString().Replace("\r\n", "\n");
    }

    private static void ValidateUniqueValues(ConsumerRepository consumer, ValidationReport report)
    {
        foreach (var group in consumer.UseCases.GroupBy(useCase => useCase.Metadata.Id, StringComparer.Ordinal).Where(group => group.Count() > 1))
        {
            report.Error("USE_CASE_ID", $"Use-case ID {group.Key} is duplicated: {string.Join(", ", group.Select(item => item.Path))}.");
        }

        foreach (var group in consumer.UseCases.SelectMany(useCase => useCase.AcceptanceCriteria.Select(id => (Id: id, UseCase: useCase))).GroupBy(item => item.Id, StringComparer.Ordinal).Where(group => group.Count() > 1))
        {
            report.Error("ACCEPTANCE_ID", $"Acceptance ID {group.Key} is duplicated: {string.Join(", ", group.Select(item => item.UseCase.Path))}.");
        }
    }

    private static void ValidatePaths(ConsumerRepository consumer, ValidationReport report)
    {
        ValidateFile(consumer, consumer.Project.Paths.ApiSolution, "PROJECT_API_SOLUTION", report);
        ValidateDirectory(consumer, consumer.Project.Paths.DomainDocs, "PROJECT_DOMAIN_DOCS", report);
        ValidateDirectory(consumer, consumer.Project.Paths.UiDocs, "PROJECT_UI_DOCS", report);
        foreach (var frontend in consumer.Project.Paths.Frontends)
        {
            ValidateDirectory(consumer, frontend.Path, "PROJECT_FRONTEND", report);
        }
    }

    private static void ValidateFile(
        ConsumerRepository consumer,
        string relativePath,
        string code,
        ValidationReport report)
    {
        var path = Path.Combine(consumer.Root, relativePath.Replace('/', Path.DirectorySeparatorChar));
        if (!File.Exists(path))
        {
            report.Error(code, "Configured file does not exist.", relativePath);
        }
    }

    private static void ValidateDirectory(
        ConsumerRepository consumer,
        string relativePath,
        string code,
        ValidationReport report)
    {
        var path = Path.Combine(consumer.Root, relativePath.Replace('/', Path.DirectorySeparatorChar));
        if (!Directory.Exists(path))
        {
            report.Error(code, "Configured directory does not exist.", relativePath);
        }
    }

    private static void ValidateRecipes(StandardsRepository standards, ConsumerRepository consumer, ValidationReport report)
    {
        var enabled = consumer.Project.Recipes.ToHashSet(StringComparer.Ordinal);
        foreach (var useCase in consumer.UseCases)
        {
            foreach (var recipe in useCase.Metadata.Recipes)
            {
                if (!standards.Manifest.Recipes.ContainsKey(recipe))
                {
                    report.Error("USE_CASE_RECIPE", $"Use case references unknown recipe {recipe}.", useCase.Path);
                }
                else if (!enabled.Contains(recipe))
                {
                    report.Error("USE_CASE_RECIPE", $"Use case references recipe {recipe}, but standards.project.json does not enable it.", useCase.Path);
                }
            }
        }
    }

    private static void ValidatePages(ConsumerRepository consumer, ValidationReport report)
    {
        var useCaseIds = consumer.UseCases.Select(useCase => useCase.Metadata.Id).ToHashSet(StringComparer.Ordinal);
        foreach (var page in consumer.Pages)
        {
            foreach (var useCase in page.Metadata.UseCases)
            {
                if (!useCaseIds.Contains(useCase))
                {
                    report.Error("PAGE_USE_CASE", $"Page references unknown use case {useCase}.", page.Path);
                }
            }
        }
    }

    private static string RelativeMarkdownLink(string from, string to)
    {
        var fromDirectory = Path.GetDirectoryName(from.Replace('/', Path.DirectorySeparatorChar)) ?? ".";
        return Path.GetRelativePath(fromDirectory, to.Replace('/', Path.DirectorySeparatorChar)).Replace('\\', '/');
    }
}
