using Litenova.Standards.Models;

namespace Litenova.Standards.Services;

internal static class StandardsGenerator
{
    public const string GeneratedMarker = "Generated by Litenova.Standards.Tool. Do not edit by hand.";

    public static IReadOnlyDictionary<string, string> Render(StandardsRepository repository)
    {
        var documentIndex = repository.Documents.Select(document => new
        {
            document.Metadata.Id,
            document.Metadata.Kind,
            document.Metadata.Normative,
            document.Metadata.AppliesTo,
            document.Metadata.Recipes,
            path = document.RelativePath,
            document.WordCount,
            rules = document.Rules.Select(rule => rule.Id).OrderBy(id => id, StringComparer.Ordinal).ToArray(),
        }).ToArray();

        var ruleCatalog = repository.Documents
            .SelectMany(document => document.Rules)
            .OrderBy(rule => rule.Id, StringComparer.Ordinal)
            .Select(rule => new
            {
                rule.Id,
                rule.Title,
                path = rule.Document,
                rule.Line,
            })
            .ToArray();

        var recipeIndex = repository.Recipes.Values
            .OrderBy(recipe => recipe.Id, StringComparer.Ordinal)
            .Select(recipe => new
            {
                recipe.Id,
                recipe.Version,
                recipe.Entry,
                recipe.Triggers,
                recipe.Replaces,
                recipe.Projects,
                recipe.Gates,
            })
            .ToArray();

        var loadPlans = repository.Manifest.LoadPlans
            .OrderBy(pair => pair.Key, StringComparer.Ordinal)
            .ToDictionary(
                pair => pair.Key,
                pair => new
                {
                    pair.Value.Tier0,
                    pair.Value.Tier1,
                    pair.Value.Tier2,
                },
                StringComparer.Ordinal);

        return new Dictionary<string, string>(StringComparer.Ordinal)
        {
            ["generated/document-index.json"] = RenderEnvelope(documentIndex),
            ["generated/rule-catalog.json"] = RenderEnvelope(ruleCatalog),
            ["generated/recipe-index.json"] = RenderEnvelope(recipeIndex),
            ["generated/load-plans.json"] = RenderEnvelope(loadPlans),
        };
    }

    public static void Write(StandardsRepository repository)
    {
        foreach (var (relativePath, content) in Render(repository))
        {
            var path = Path.Combine(repository.Root, relativePath.Replace('/', Path.DirectorySeparatorChar));
            Directory.CreateDirectory(Path.GetDirectoryName(path)!);
            File.WriteAllText(path, content);
        }
    }

    public static ValidationReport Check(StandardsRepository repository)
    {
        var report = new ValidationReport();
        foreach (var (relativePath, expected) in Render(repository))
        {
            var path = Path.Combine(repository.Root, relativePath.Replace('/', Path.DirectorySeparatorChar));
            if (!File.Exists(path))
            {
                report.Error("GENERATED_MISSING", "Generated file is missing.", relativePath);
                continue;
            }

            var actual = File.ReadAllText(path).Replace("\r\n", "\n");
            if (!string.Equals(actual, expected, StringComparison.Ordinal))
            {
                report.Error("GENERATED_STALE", "Generated file is stale. Run standards generate.", relativePath);
            }
        }

        return report;
    }

    private static string RenderEnvelope<T>(T data) => JsonSupport.Serialize(new
    {
        generated = GeneratedMarker,
        data,
    });
}

