<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../__PROJECT__.Domain/__PROJECT__.Domain.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="LiteBus.Commands.Abstractions" />
    <PackageReference Include="LiteBus.Events.Abstractions" />
    <PackageReference Include="LiteBus.Queries.Abstractions" />
    <PackageReference Include="Marten" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="__PROJECT__.Application.Tests" />
  </ItemGroup>
</Project>

